export const FACULTIES = {
  "Faculty of Arts": [
    "Anthropology",
    "Bimodal Bilingual Studies",
    "Chinese Language and Literature",
    "Chinese Studies",
    "English",
    "Fine Arts",
    "History",
    "Japanese Studies",
    "Linguistics",
    "Music",
    "Philosophy",
    "Public History",
    "Public Humanities",
    "Religious Studies",
    "Theology",
    "Translation",
  ],
  "Faculty of Business Administration": [
    "BBA(IBBA)-JD Double Degree Programme",
    "Biotechnology, Entrepreneurship and Healthcare Management",
    "Global Business Studies",
    "Global Economics and Finance",
    "Hospitality and Real Estate",
    "Insurance, Financial and Actuarial Analysis",
    "Integrated Bachelor of Business Administration Programme",
    "Interdisciplinary Data Analytics & X Double Major",
    "Professional Accountancy",
    "Quantitative Finance",
    "Quantitative Finance and Risk Management Science",
  ],
  "Faculty of Education": [
    "Chinese Language Studies (BA) and Chinese Language Education (BEd)",
    "Early Childhood Education",
    "Early Childhood Education (BA)",
    "English Studies (BA) and English Language Education (BEd)",
    "Exercise Science and Health Education",
    "Human Movement Science and Health Studies",
    "Learning Design and Technology",
    "Mathematics and Mathematics Education",
    "Physical Education, Exercise Science and Health",
  ],
  "Faculty of Engineering": [
    "Aerospace Science and Earth Informatics & X Double Major Programme",
    "Artificial Intelligence: Systems and Technologies",
    "Biomedical Engineering",
    "Computational Data Science",
    "Computer Engineering",
    "Computer Science",
    "Computer Science and Engineering",
    "Electronic Engineering",
    "Energy and Environmental Engineering",
    "Financial Technology",
    "Information Engineering",
    "Interdisciplinary Data Analytics & X Double Major Programme",
    "Learning Design and Technology",
    "Materials Science and Engineering",
    "Mathematics and Information Engineering",
    "Mechanical and Automation Engineering",
    "Systems Engineering and Engineering Management",
  ],
  "Faculty of Law": ["BBA(IBBA)-JD Double Degree Programme", "Laws"],
  "Faculty of Medicine": [
    "Biomedical Sciences",
    "Biotechnology, Entrepreneurship and Healthcare Management",
    "Chinese Medicine",
    "Community Health Practice",
    "Gerontology",
    "Medicine (MBChB) Programme / Medicine (MBChB) Programme Global Physician-Leadership Stream (GPS)",
    "Nursing",
    "Pharmacy",
    "Public Health",
  ],
  "Faculty of Science": [
    "Aerospace Science and Earth Informatics & X Double Major Programme",
    "Biotechnology, Entrepreneurship and Healthcare Management",
    "Computational Data Science",
    "Earth and Environmental Sciences",
    "Enrichment Mathematics",
    "Enrichment Stream in Theoretical Physics",
    "Interdisciplinary Data Analytics & X Double Major Programme",
    "Learning Design and Technology",
    "Materials Science and Engineering",
    "Mathematics and Information Engineering",
    "Natural Sciences",
    "Quantitative Finance and Risk Management Science",
    "Risk Management Science",
    "Science",
  ],
  "Faculty of Social Science": [
    "Aerospace Science and Earth Informatics & X Double Major Programme",
    "Architectural Studies",
    "Data Science and Policy Studies",
    "Economics",
    "Economics (CUHK-Tsinghua University Dual Undergraduate Degree Programme)",
    "Gender Studies",
    "Geography and Resource Management",
    "Global Communication",
    "Global Economics and Finance",
    "Global Studies",
    "Government and Public Administration",
    "Journalism and Communication",
    "Psychology",
    "Social Science (Broad-based)",
    "Social Work",
    "Society and Sustainable Development",
    "Sociology",
    "Urban Studies",
  ],
} as const;

export type Faculty = keyof typeof FACULTIES;
export type Major = (typeof FACULTIES)[Faculty][number];

export const FACULTY_LIST = Object.keys(FACULTIES) as Faculty[];
